name: build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    container: python:3.9-alpine
    env:
      CRYPTOGRAPHY_DONT_BUILD_RUST: 1

    steps:
    - uses: actions/checkout@v2

    - name: Install packages
      run: apk --update --no-cache add gcc libc-dev libffi-dev openssl-dev

    - name: Install twine
      run: pip install twine

    - name: Install pybuilder
      run: pip install pybuilder

    - name: Install dependencies
      run: pyb install_dependencies

    - name: Execute build
      run: pyb -X --no-venvs

    - name: Install Codecov requirements
      run: |
        apk update
        apk add bash curl
        sed -e 's,filename="mplogp/,filename="src/main/python/mplogp/,g' target/reports/mplogp_coverage.xml > coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
